name : outputs-example

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            BUILD_TIME: ${{ steps.get_time.outputs.BUILD_TIME }}

        steps:
            - name: Get build time
              id: get_time
              run: echo "BUILD_TIME=$(date)" >> $GITHUB_OUTPUT
            - name: Show build time
              run: echo "Build time is ${{ steps.get_time.outputs.BUILD_TIME }}"
            - name: deploy on production
              if: ${{ github.ref == 'refs/heads/main' }}
              run: echo "Deploying to production server "
            - name: deploy on staging
              if: ${{ github.ref == 'refs/heads/staging' }}
              run: echo "Deploying to staging server "
            - name: if event name
              if : ${{ github.event_name == 'push' }}
              run: echo "The event is a push event"
    
    build-differnet-os:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [14, 16, 18]
        steps:
            - name: Check OS
              run: echo "This job is running on ${{ matrix.os }}"

            - name: if node version
              if: ${{ matrix.node == 16 }} &&
                  ${{ matrix.os == 'ubuntu-latest' }}
              run: npm install -g npm@latest 
